# FAÇA UM PROGRAMA QUE LEIA A LARGURA E A ALTURA DE UMA PAREDE EM METROS, CALCULE A SUA ÁREA E A QUANTIDADE DE TINTA NECESSÁRIA PARA PINTÁ-LO,
# SABENDO QUE CADA LITRO DE TINRA, PINTA UMA ÁREA DE 2M^2
